# Generated by Django 6.0.4 on 2026-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_estudiante", models.CharField(max_length=150)),
                ("identificacion", models.CharField(max_length=15)),
                ("asignatura", models.CharField(max_length=100)),
                ("nota1", models.DecimalField(decimal_places=2, max_digits=5)),
                ("nota2", models.DecimalField(decimal_places=2, max_digits=5)),
                ("nota3", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "promedio",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "Calificación",
                "verbose_name_plural": "Calificaciones",
                "ordering": ["nombre_estudiante"],
            },
        ),
    ]
